### ISSUE TITLE
can't run: NameError: name 'dataset' is not defined

### ISSUE THREAD

**Issue by zhyunlong** [EhsanAghazadeh/Metaphors_in_PLMs#1]
I can't run the code following readme. 
The code gets wrong in  line 555 in json_to_df. The information is "NameError: name 'dataset' is not defined". And I can't find the defination of dataset.
Does anyting wrong?

**Comment by mohsenfayyaz** [comment]
Hi @zhyunlong, 
Thanks for reporting this issue.
The code is updated and a colab notebook for running probings is provided at [Metaphor_Demo.ipynb](https://github.com/EhsanAghazadeh/Metaphors_in_PLMs/blob/main/Metaphor_Demo.ipynb).

**Comment by zhyunlong** [comment]
Thanks for your reply. But I am still confused. I see in mdl_probing.py, the test set is not used. The test set which is used for  caculating metrice is the half of train set (the last portion). 
Do I  miss somewhere in paper mentioned this evaluation setting, or it's common way in mdl probing ?

**Comment by zhyunlong** [comment]
hey, I read the code and paper again. and Do the last portion's metrics is final metrics? Appreicate for your reply.

**Comment by mohsenfayyaz** [comment]
Hey, Thanks for your interest in our work.
Yes, the last portion metrics are the final metrics, and the "online_codelength" is accumulated throughout portions. [mdl_probing.py#L1308](https://github.com/EhsanAghazadeh/Metaphors_in_PLMs/blob/48b0f7adb97dc6c9e4e8bcc02bd4b83d4b6b2219/source_code/scripts/mdl_probing.py#L1308)
We have implemented the "Online Coding" method, and here is a well-written blog post about it: https://lena-voita.github.io/posts/mdl_probes.html
